### PR TITLE
Support multiple temporary folders; Support tmp folder on class level.

### PR DESCRIPTION
**Pull request by ChristianCiach**
* Multiple temporary folders are supported by using the ParameterContext
as key of the Store.

* Do not destroy temporary folder prematurely when used on class level
(@BeforeAll), instead of method level (@BeforeEach). This is done by
implementing ClosableResource, which requires JUnit Jupiter at version
5.1.

## Further Comments

Sorry for having two different changes in one pull request. I just wanted to give back my local changes to the extension, without putting too much work into it. Feel free to merge or to close :)

By depending on version 5.1 of JUnit Jupiter, this drastically simplifies the implementation of the TemporaryFolderExtension, as TemporaryFolder.close() now automatically gets called when the ExtensionContext dies. Before, the temporary folder got destroyed on @AfterEach, which was a problem when the folder was used at class level by the unit test.

I deleted the TemporaryFolderExtensionMetaTest, because it tests removed methods of the extension and I was too lazy to write a test for the changes I did to the extension.

By using the ParameterContext as the key of the store, multiple instances of TemporaryFolder are now supported, as the context is different for each parameter index.

Again, feel free to merge or not merge any of my changes or be inspired by them :)

### CODE REVIEW

**Comment by glytching** [comment]
Thanks for the PR.

Are there any tests covering this change? If I understand the change correctly then I'd expect to see tests covering the following scenarios:

* When declaring a class level `TemporaryFolder` ...
    * The same instance is used by all tests in the class
    * This instance is destroyed after execution of the test case
* When declaring a method level `TemporaryFolder` ...
    * This instance is destroyed after execution of the test method

**Comment by ChristianCiach** [comment]
@glytching See my edited comment above. Sorry, I won't add unit tests for the changes. I did these changes for work and just wanted to give back my modifications without additional work on my side.

**Comment by glytching** [comment]
Ok, I'll take it from there.

Thanks again.

**Comment by glytching** [comment]
Covered by https://github.com/glytching/junit-extensions/pull/12.

Thanks for your help.

**Pull request closed without merging**
